// Minimal backup country data for when API fails
export const backupCountries = [
  {
    name: { common: "United States", official: "United States of America" },
    capital: ["Washington, D.C."],
    region: "Americas",
    population: 331002651,
    flags: {
      png: "https://flagcdn.com/w320/us.png",
      svg: "https://flagcdn.com/us.svg",
    },
    cca3: "USA",
    languages: { eng: "English" },
    currencies: { USD: { name: "United States dollar", symbol: "$" } },
  },
  {
    name: { common: "Canada", official: "Canada" },
    capital: ["Ottawa"],
    region: "Americas",
    population: 38008005,
    flags: {
      png: "https://flagcdn.com/w320/ca.png",
      svg: "https://flagcdn.com/ca.svg",
    },
    cca3: "CAN",
    languages: { eng: "English", fra: "French" },
    currencies: { CAD: { name: "Canadian dollar", symbol: "$" } },
  },
  {
    name: {
      common: "United Kingdom",
      official: "United Kingdom of Great Britain and Northern Ireland",
    },
    capital: ["London"],
    region: "Europe",
    population: 67886011,
    flags: {
      png: "https://flagcdn.com/w320/gb.png",
      svg: "https://flagcdn.com/gb.svg",
    },
    cca3: "GBR",
    languages: { eng: "English" },
    currencies: { GBP: { name: "British pound", symbol: "£" } },
  },
  {
    name: { common: "Germany", official: "Federal Republic of Germany" },
    capital: ["Berlin"],
    region: "Europe",
    population: 83240525,
    flags: {
      png: "https://flagcdn.com/w320/de.png",
      svg: "https://flagcdn.com/de.svg",
    },
    cca3: "DEU",
    languages: { deu: "German" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
  },
  {
    name: { common: "France", official: "French Republic" },
    capital: ["Paris"],
    region: "Europe",
    population: 67391582,
    flags: {
      png: "https://flagcdn.com/w320/fr.png",
      svg: "https://flagcdn.com/fr.svg",
    },
    cca3: "FRA",
    languages: { fra: "French" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
  },
  {
    name: { common: "Japan", official: "Japan" },
    capital: ["Tokyo"],
    region: "Asia",
    population: 125836021,
    flags: {
      png: "https://flagcdn.com/w320/jp.png",
      svg: "https://flagcdn.com/jp.svg",
    },
    cca3: "JPN",
    languages: { jpn: "Japanese" },
    currencies: { JPY: { name: "Japanese yen", symbol: "¥" } },
  },
  {
    name: { common: "Australia", official: "Commonwealth of Australia" },
    capital: ["Canberra"],
    region: "Oceania",
    population: 25687041,
    flags: {
      png: "https://flagcdn.com/w320/au.png",
      svg: "https://flagcdn.com/au.svg",
    },
    cca3: "AUS",
    languages: { eng: "English" },
    currencies: { AUD: { name: "Australian dollar", symbol: "$" } },
  },
  {
    name: { common: "Brazil", official: "Federative Republic of Brazil" },
    capital: ["Brasília"],
    region: "Americas",
    population: 214262622,
    flags: {
      png: "https://flagcdn.com/w320/br.png",
      svg: "https://flagcdn.com/br.svg",
    },
    cca3: "BRA",
    languages: { por: "Portuguese" },
    currencies: { BRL: { name: "Brazilian real", symbol: "R$" } },
  },
];
